import { useMemo } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export interface AutomatedEvent {
  id: string;
  type: 'secado' | 'palpacion' | 'vacuna' | 'desparasitacion' | 'revision' | 'destete';
  animalId: string;
  tagId: string;
  name: string | null;
  scheduledDate: string;
  daysUntil: number;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  description: string;
  basedOn: string;
  autoGenerated: boolean;
}

interface Animal {
  id: string;
  tag_id: string;
  name: string | null;
  category: string;
  sex: string;
  birth_date?: string | null;
  last_calving_date?: string | null;
  expected_calving_date?: string | null;
  last_service_date?: string | null;
  reproductive_status?: string | null;
}

// Configuración de eventos automáticos
const EVENT_RULES = {
  // Secado: 60 días antes del parto esperado
  secado: { daysBeforeCalving: 60 },
  // Palpación: 35-45 días después del servicio
  palpacion: { daysAfterService: 40 },
  // Destete: 6-8 meses después del nacimiento
  destete: { daysAfterBirth: 210 },
  // Revisión post-parto: 21-30 días después del parto
  revisionPostParto: { daysAfterCalving: 25 },
  // Primera vacuna terneros: 3 meses
  primeraVacuna: { daysAfterBirth: 90 },
};

/**
 * Hook para generar eventos automáticos basados en resultados
 * Funcionalidad de alta prioridad del análisis InterHerd
 */
export function useAutomatedEvents(animals: Animal[]) {
  const { toast } = useToast();

  /**
   * Genera todos los eventos automáticos basados en el estado actual de los animales
   */
  const generatedEvents = useMemo((): AutomatedEvent[] => {
    const events: AutomatedEvent[] = [];
    const today = new Date();

    animals.forEach(animal => {
      // 1. SECADO: Para vacas preñadas cerca del parto
      if (animal.expected_calving_date && animal.reproductive_status === 'preñada') {
        const calvingDate = new Date(animal.expected_calving_date);
        const secadoDate = new Date(calvingDate);
        secadoDate.setDate(secadoDate.getDate() - EVENT_RULES.secado.daysBeforeCalving);
        
        const daysUntil = Math.ceil((secadoDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
        
        if (daysUntil >= -7 && daysUntil <= 30) {
          events.push({
            id: `secado-${animal.id}`,
            type: 'secado',
            animalId: animal.id,
            tagId: animal.tag_id,
            name: animal.name,
            scheduledDate: secadoDate.toISOString().split('T')[0],
            daysUntil,
            priority: daysUntil < 0 ? 'urgent' : daysUntil <= 7 ? 'high' : 'medium',
            description: `Secado programado 60 días antes del parto`,
            basedOn: `Parto esperado: ${new Date(animal.expected_calving_date).toLocaleDateString('es-ES')}`,
            autoGenerated: true
          });
        }
      }

      // 2. PALPACIÓN: Para vacas servidas sin confirmar
      if (animal.last_service_date && animal.reproductive_status === 'servida') {
        const serviceDate = new Date(animal.last_service_date);
        const palpacionDate = new Date(serviceDate);
        palpacionDate.setDate(palpacionDate.getDate() + EVENT_RULES.palpacion.daysAfterService);
        
        const daysUntil = Math.ceil((palpacionDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
        
        if (daysUntil >= -14 && daysUntil <= 30) {
          events.push({
            id: `palpacion-${animal.id}`,
            type: 'palpacion',
            animalId: animal.id,
            tagId: animal.tag_id,
            name: animal.name,
            scheduledDate: palpacionDate.toISOString().split('T')[0],
            daysUntil,
            priority: daysUntil < 0 ? 'urgent' : daysUntil <= 5 ? 'high' : 'medium',
            description: `Palpación para confirmar preñez`,
            basedOn: `Servicio: ${new Date(animal.last_service_date).toLocaleDateString('es-ES')}`,
            autoGenerated: true
          });
        }
      }

      // 3. REVISIÓN POST-PARTO: Para vacas que acaban de parir
      if (animal.last_calving_date) {
        const calvingDate = new Date(animal.last_calving_date);
        const revisionDate = new Date(calvingDate);
        revisionDate.setDate(revisionDate.getDate() + EVENT_RULES.revisionPostParto.daysAfterCalving);
        
        const daysUntil = Math.ceil((revisionDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
        
        if (daysUntil >= -7 && daysUntil <= 14) {
          events.push({
            id: `revision-${animal.id}`,
            type: 'revision',
            animalId: animal.id,
            tagId: animal.tag_id,
            name: animal.name,
            scheduledDate: revisionDate.toISOString().split('T')[0],
            daysUntil,
            priority: daysUntil < 0 ? 'high' : 'medium',
            description: `Revisión uterina post-parto`,
            basedOn: `Parto: ${new Date(animal.last_calving_date).toLocaleDateString('es-ES')}`,
            autoGenerated: true
          });
        }
      }

      // 4. DESTETE: Para terneros de 6-8 meses
      if (animal.birth_date && (animal.category === 'ternero' || animal.category === 'ternera')) {
        const birthDate = new Date(animal.birth_date);
        const desteteDate = new Date(birthDate);
        desteteDate.setDate(desteteDate.getDate() + EVENT_RULES.destete.daysAfterBirth);
        
        const daysUntil = Math.ceil((desteteDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
        
        if (daysUntil >= -14 && daysUntil <= 30) {
          events.push({
            id: `destete-${animal.id}`,
            type: 'destete',
            animalId: animal.id,
            tagId: animal.tag_id,
            name: animal.name,
            scheduledDate: desteteDate.toISOString().split('T')[0],
            daysUntil,
            priority: daysUntil < 0 ? 'high' : daysUntil <= 7 ? 'medium' : 'low',
            description: `Destete programado (7 meses)`,
            basedOn: `Nacimiento: ${new Date(animal.birth_date).toLocaleDateString('es-ES')}`,
            autoGenerated: true
          });
        }
      }

      // 5. PRIMERA VACUNA: Para terneros de 3 meses
      if (animal.birth_date && (animal.category === 'becerro' || animal.category === 'becerra' || 
          animal.category === 'ternero' || animal.category === 'ternera')) {
        const birthDate = new Date(animal.birth_date);
        const vacunaDate = new Date(birthDate);
        vacunaDate.setDate(vacunaDate.getDate() + EVENT_RULES.primeraVacuna.daysAfterBirth);
        
        const daysUntil = Math.ceil((vacunaDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
        
        if (daysUntil >= -7 && daysUntil <= 21) {
          events.push({
            id: `vacuna-${animal.id}`,
            type: 'vacuna',
            animalId: animal.id,
            tagId: animal.tag_id,
            name: animal.name,
            scheduledDate: vacunaDate.toISOString().split('T')[0],
            daysUntil,
            priority: daysUntil < 0 ? 'urgent' : daysUntil <= 7 ? 'high' : 'medium',
            description: `Primera vacunación (Clostridiales)`,
            basedOn: `Edad: 3 meses`,
            autoGenerated: true
          });
        }
      }
    });

    // Ordenar por prioridad y fecha
    const priorityOrder = { urgent: 0, high: 1, medium: 2, low: 3 };
    return events.sort((a, b) => {
      if (priorityOrder[a.priority] !== priorityOrder[b.priority]) {
        return priorityOrder[a.priority] - priorityOrder[b.priority];
      }
      return a.daysUntil - b.daysUntil;
    });
  }, [animals]);

  /**
   * Eventos urgentes (vencidos o próximos 3 días)
   */
  const urgentEvents = useMemo(() => {
    return generatedEvents.filter(e => e.daysUntil <= 3);
  }, [generatedEvents]);

  /**
   * Eventos por tipo
   */
  const eventsByType = useMemo(() => {
    const byType: Record<string, AutomatedEvent[]> = {};
    generatedEvents.forEach(e => {
      if (!byType[e.type]) byType[e.type] = [];
      byType[e.type].push(e);
    });
    return byType;
  }, [generatedEvents]);

  /**
   * Resumen de eventos
   */
  const summary = useMemo(() => {
    return {
      total: generatedEvents.length,
      urgent: generatedEvents.filter(e => e.priority === 'urgent').length,
      high: generatedEvents.filter(e => e.priority === 'high').length,
      medium: generatedEvents.filter(e => e.priority === 'medium').length,
      low: generatedEvents.filter(e => e.priority === 'low').length,
      byType: {
        secado: eventsByType['secado']?.length || 0,
        palpacion: eventsByType['palpacion']?.length || 0,
        destete: eventsByType['destete']?.length || 0,
        vacuna: eventsByType['vacuna']?.length || 0,
        revision: eventsByType['revision']?.length || 0,
      }
    };
  }, [generatedEvents, eventsByType]);

  /**
   * Marcar evento como completado
   */
  const completeEvent = async (event: AutomatedEvent) => {
    // Esta función registraría el evento en la base de datos correspondiente
    // Por ahora solo muestra un toast
    toast({
      title: 'Evento completado',
      description: `${event.type} de ${event.tagId} registrado correctamente`
    });
  };

  /**
   * Posponer evento
   */
  const postponeEvent = (event: AutomatedEvent, days: number) => {
    toast({
      title: 'Evento pospuesto',
      description: `${event.type} de ${event.tagId} pospuesto ${days} días`
    });
  };

  return {
    generatedEvents,
    urgentEvents,
    eventsByType,
    summary,
    completeEvent,
    postponeEvent
  };
}
